# KiloMenos - Secrets Template
# Copy this file to 'secrets.properties' and fill in the real values.
# DO NOT commit 'secrets.properties' to version control.

DEV_API_KEY=
DEV_ADMOB_APP_ID=
DEV_ADMOB_BANNER_ID=
DEV_GOOGLE_WEB_CLIENT_ID=

PRO_API_KEY=
PRO_ADMOB_APP_ID=
PRO_ADMOB_BANNER_ID=
PRO_GOOGLE_WEB_CLIENT_ID=
